name: Deploy Backend to AWS EC2

on:
  push:
    branches:
      - main
    paths:
      - "backend/**" # This pipeline only runs if backend code changes

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 1. Clone or update the code on the server
            if [ ! -d "task-manger-todo-with-authentication" ]; then
              git clone https://github.com/superansh55/task-manger-todo-with-authentication.git
            fi
            cd task-manger-todo-with-authentication
            git pull origin main

            # 2. Go to the backend directory
            cd backend

            # 3. Stop and remove the old container if it exists
            sudo docker stop ansh-task-backend || true
            sudo docker rm ansh-task-backend || true

            # 4. Build the new Docker image
            sudo docker build -t ansh-task-backend .

            # 5. Run the new container, injecting database secrets securely
            sudo docker run -d \
              --name ansh-task-backend \
              -p 4000:4000 \
              -e MONGO_URI="${{ secrets.MONG_URI }}" \
              -e JWT_SECRET="${{ secrets.SECRET }}" \
              ansh-task-backend
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      # 1. Grab your code from GitHub
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Install Node.js on the GitHub runner
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # 3. Build the React app
      - name: Install dependencies and Build
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      # 4. Log into AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 5. Sync the compiled files to S3
      - name: Deploy to S3
        run: |
          aws s3 sync frontend/dist s3://ansh-task-manager-frontend-998877 --delete
